### PR TITLE
Index changes

### PR DESCRIPTION
**Pull request by michael-yin**

### CODE REVIEW

**Comment by seb-b** [comment]
Hi @michael-yin, 

Can I ask the thinking behind the switch to a one-to-one index to model relationship? The way I had it search would be across children of indexed objects. So for example say you had a model setup like this:
```
Page ---
        |--- HomePage
        |--- ContentPage
        |--- etc.
```
A search like `backend.search('example', Page)` will only search over the `Page` indexed fields, and the indexed fields of `HomePage`, `ContentPage` and join the results. 

It would of been useful to have gotten feedback on #5 so we could have discussed the changes.

**Comment by seb-b** [comment]
Rereading the pr, I see that it indexes one-to-one but searches the subclasses, that makes sense :+1: 

Why was the ability to change the search operator removed?

**Comment by michael-yin** [comment]
Hi, @seb-b 

Thanks for your message, I also plan to send you message today to let you review my code.

1. Yes, we can deal with subclass when searching, so we can only change one index if our object has been updated or deleted. I did tests, it seems working.

2. I do not quite understand `search operator ` you mean, is it code below?

```
def _get_group(self):
    if self.operator and self.operator == 'and':
        return qparser.AndGroup
    elif isinstance(self.query, PlainText):
        if self.query.operator == 'and':
            return qparser.AndGroup
    return qparser.OrGroup
```

Thanks.

**Comment by seb-b** [comment]
Excellent, should cut down on indexing time :smiley: 
Yep, that allowed the operator to be changed, like the examples in the wagtail docs here: https://docs.wagtail.io/en/v2.5.1/topics/search/searching.html#search-operator

**Comment by seb-b** [comment]
@michael-yin on my branch I added this on line in `_do_search`:
```
results = searcher.search(query, limit=None)
print(results)
score_map = dict([(r[PK], r.score) for r in results])
```

Then running `./runtests.py tests.test_backend.TestWhooshSearchBackend.test_search_and_operator`

The print statement outputs:
```
<Top 1 Results for And([Or([Term('title', 'java'), Term('title', 'avas'), Term('title', 'vasc'), Term('title', 'ascr'), Term('title', 'scri'), Term('title', 'crip'), Term('title', 'ript'), Term('title_filter', 'javascript'), Term('authors_filter', 'javascript'), Term('authors__name', 'javascript'), Term('authors__date_of_birth_filter', 'javascript'), Term('publication_date_filter', 'javascript'), Term('number_of_pages_filter', 'javascript'), Term('tags__name', 'javascript'), Term('tags__slug_filter', 'javascript'), Term('tags_filter', 'javascript')]), Or([Term('title', 'defi'), Term('title', 'efin'), Term('title', 'fini'), Term('title', 'init'), Term('title', 'niti'), Term('title', 'itiv'), Term('title', 'tive'), Term('title_filter', 'definitive'), Term('authors_filter', 'definitive'), Term('authors__name', 'definitive'), Term('authors__date_of_birth_filter', 'definitive'), Term('publication_date_filter', 'definitive'), Term('number_of_pages_filter', 'definitive'), Term('tags__name', 'definitive'), Term('tags__slug_filter', 'definitive'), Term('tags_filter', 'definitive')])]) runtime=0.004833498009247705>
```

Note the `And` at the start.

If I override the `test_search_and_operator` test and change `and` to `or` the print statement gives the following:

```
<Top 2 Results for Or([Term('title', 'java'), Term('title', 'avas'), Term('title', 'vasc'), Term('title', 'ascr'), Term('title', 'scri'), Term('title', 'crip'), Term('title', 'ript'), Term('title_filter', 'javascript'), Term('authors_filter', 'javascript'), Term('authors__name', 'javascript'), Term('authors__date_of_birth_filter', 'javascript'), Term('publication_date_filter', 'javascript'), Term('number_of_pages_filter', 'javascript'), Term('tags__name', 'javascript'), Term('tags__slug_filter', 'javascript'), Term('tags_filter', 'javascript'), Term('title', 'defi'), Term('title', 'efin'), Term('title', 'fini'), Term('title', 'init'), Term('title', 'niti'), Term('title', 'itiv'), Term('title', 'tive'), Term('title_filter', 'definitive'), Term('authors_filter', 'definitive'), Term('authors__name', 'definitive'), Term('authors__date_of_birth_filter', 'definitive'), Term('publication_date_filter', 'definitive'), Term('number_of_pages_filter', 'definitive'), Term('tags__name', 'definitive'), Term('tags__slug_filter', 'definitive'), Term('tags_filter', 'definitive')])
```

and the test fails

I'm not sure why the test passes on this branch after the code has been removed

**Comment by michael-yin** [comment]
@seb-b 

`query` generated by `query_compiler.get_whoosh_query` have a `JOINT` varaible.

If you search `javascript AND definition`, the `JOINT` is `AND` even if you do not set the `group` variable. I did not check more code for this but I think that is why my branch pass the unit test without using `group` (maybe it would check search expression?)

And I think if the code can work fine with `or` and `and` of `PlainText`, we do not need add `group` here. I still want to keep the code clean.

Thanks.

**Pull request merged**
